name: "Auth Service Build and Push"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "auth/**"
  pull_request:
    branches: [main]
    paths:
      - "auth/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Build and test
        run: npm ci
        working-directory: auth

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./auth
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tomato-auth-service:latest
